package tw.waterballsa.gaas.exceptions.enums

enum class PlatformError(
    val code: String,
) {

    CLIENT_INVALID("C001"),
    CLIENT_AUTHORIZATION_INVALID("C002"),

    JWT_ERROR("J001"),
    JWT_NOT_FOUND("J002"),

    GAME_NOT_FOUND("G001"),
    GAME_EXISTS("G002"),
    GAME_CREATE_ERROR("G003"),
    GAME_ALREADY_STARTED("G004"),
    GAME_START_FAILED("G005"),

    USER_NOT_FOUND("U001"),
    USER_INPUT_INVALID("U002"),
    USER_NAME_DUPLICATED("U003"),

    ROOM_NOT_FOUND("R001"),
    ROOM_PASSWORD_INCORRECT("R002"),
    ROOM_FULL("R003"),

    PLAYER_NOT_FOUND("P001"),
    PLAYER_NOT_HOST("P002"),
    PLAYER_JOIN_ROOM_ERROR("P003"),
    PLAYER_CREATE_ROOM_ERROR("P004"),
    PLAYER_NOT_IN_ROOM_ERROR("P005"),
}
